Repository ServiceNow/SyGra, pull requests merged in 2025-09, with the labels that each got.

#19 [Documentation] Update Image links
  README.md
  docs/getting_started/model_configuration.md
Labels: documentation

#21 [Enhancement] Support langchain tools
  docs/concepts/nodes/agent_node.md
  grasp/utils/tool_utils.py
Labels: enhancement

#20 [Enhancement] Support for Python 3.9+
  .github/workflows/tests.yaml
  Makefile
  apps/create_from_template.py
  apps/create_new_task.py
  apps/grasp_app.py
  apps/models.py
  apps/tasks.py
  apps/utils.py
  check.mk
  docs/development.md
  docs/installation.md
  grasp/core/dataset/dataset_processor.py
  grasp/core/dataset/huggingface_handler.py
  grasp/core/graph/edges/edge_factory.py
  grasp/core/graph/nodes/base_node.py
  grasp/core/graph/nodes/connector_node.py
  grasp/core/graph/nodes/node_utils.py
  grasp/core/graph/nodes/special_node.py
  grasp/core/models/client/client_factory.py
  grasp/core/models/client/http_client.py
  grasp/core/models/client/ollama_client.py
  grasp/core/models/client/openai_azure_client.py
  grasp/core/models/client/openai_client.py
  grasp/core/models/custom_models.py
  grasp/models/__init__.py
  grasp/setup.py
  grasp/utils/audio_utils.py
  grasp/utils/utils.py
  grasp/validators/custom_schemas.py
  mkdocs.yml
  pyproject.toml
  setup_grasp_lib.sh
  tests/conftest.py
  tests/core/models/client/test_client_factory.py
  tests/core/models/client/test_http_client.py
  tests/core/models/client/test_openai_client.py
  tests/core/models/langgraph/test_openai_chat_model.py
  tests/core/models/langgraph/test_vllm_chat_model.py
  tests/core/models/test_ollama_custom_model.py
  tests/core/models/test_structured_output_support.py
  tests/core/models/test_triton_custom_model.py
Labels: enhancement

#34 [Enhancement] Moved all workflows to run on a single env
  .github/workflows/ci.yaml
  .github/workflows/format.yaml
  .github/workflows/gh-pages.yml
  .github/workflows/lint.yaml
  .github/workflows/mkdocs-check.yml
  .github/workflows/tests.yaml
  grasp/logger/logger_config.py
Labels: enhancement

#35 [Documentation] Updating documentation
  .github/workflows/ci.yaml
  README.md
  docs/grasp_library.md
  docs/resources/images/grasp_components.png
  docs/resources/images/grasp_framework.png
  docs/resources/images/grasp_single_task_components.png
  docs/resources/images/grasp_usecase2framework.png
  pyproject.toml
Labels: documentation

#47 [Enhancement] Add publish workflow
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  README.md
Labels: enhancement

#45 [Fix] self.id_column Type Mismatch in BaseTaskExecutor
  README.md
  sygra/core/base_task_executor.py
Labels: bug
